on:
  pull_request: {}
  push:
    branches: master

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - run: sudo apt-get install -y "linux-headers-$(uname -r)"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, rust-src

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: |
            sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
            sudo apt-get install -y clang-10 libclang-10-dev
            echo "::set-env name=CC::clang-10"
            echo "::set-env name=CXX::clang++-10"
            echo "::set-env name=CLANG::clang-10"

      - run: make
      - name: Test the device
        run: |
            set -x
            sudo insmod justuse.ko
            DEVICE_NUM=$(cat /proc/devices | grep justuse | awk '{print $1}')
            echo "justuse device number is $DEVICE_NUM"
            sudo mknod --mode=0666 ./rand c $DEVICE_NUM 0
            head -c 16 ./rand | xxd
            head -c 64 ./rand | xxd
            head -c 1024 ./rand | xxd
            echo "some stuff" > ./rand
      - run: dmesg
        if: failure()

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
